[pytest]
pythonpath = src
testpaths = tests
<<<<<<< ours
<<<<<<< ours
<<<<<<< ours
<<<<<<< ours
<<<<<<< ours
<<<<<<< ours
norecursedirs = .* build dist venv .venv node_modules
=======
norecursedirs = .* build dist venv .venv node_modules
>>>>>>> theirs
=======
norecursedirs = .* build dist venv .venv node_modules
>>>>>>> theirs
=======
norecursedirs = .* build dist venv .venv node_modules
>>>>>>> theirs
=======
norecursedirs = .* build dist venv .venv node_modules
>>>>>>> theirs
=======
norecursedirs = .* build dist venv .venv node_modules
>>>>>>> theirs
=======
norecursedirs = .* build dist venv .venv node_modules
>>>>>>> theirs
